### ISSUE TITLE
API design discussion

### ISSUE THREAD

**Issue by timotheecour** [oswjk/protobuf-nim#3]
on API side, I much prefer the way it's done in [dproto](https://github.com/msoucy/dproto) ; that one is in D but IMO should be doable in nim too:

instead of:
```
let message = newTest1()
setA(message, 150)
let pbso = newProtobufStream(newFileStream(stdout))
writeTest1(pbso, message)
```
we could have:
```
let message = newTest1()
message.a = 150
assert message.a == 150
auto serializedObject = message.serialize();
auto message2 = newTest1(serializedObject);
assert message2 == message
```
and more generally for more complex example, see example in their [readme](https://github.com/msoucy/dproto/blob/master/README.md)

**Comment by oswjk** [comment]
Thank you for the suggestions!

Setting fields with the `message.a = 150` syntax is definitely something that we should have.

And I think that `serialize` proc makes it easier for the user and it can be implemented using the current stream implementation very easily.

I'll have to dig their implementation more. Thanks for the pointer!

**Comment by oswjk** [comment]
This simple attribute setting syntax and serialize/newMessage(data) have been implemented.
